server:
  port: ${PORT:8080}


spring:
  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:email-db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123456}
    initialize: true
    maxActice: 3


  
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql
  
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 9822c606cd42b0
    password: d8d12800be7995
    properties:
      mail:
        smtp:
          auth: true
          starttls: true
  
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

app-config:


  rabbit:
    exchange:
      mail: mail.exchange

    routingKey:
      mail: mail-confirmation.routingKey

    queue:
      mail: mail-confirmation.queue

