version: '3.9'
services:

  db:
    image: postgres:alpine
    container_name: db
    environment:
      - POSTGRES_DB=email-db
      - POSTGRES_DB=sender-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
  

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
networks:
  default:
    name: local
