version: '3.9'
services:

  db:
    image: mongo
    container_name: mail_rabbit
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=email
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
      - 28017:28017
      
  postgres:
    image: postgres:alpine
    container_name: db
    environment:
      - POSTGRES_DB=email-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
 
  

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
networks:
  default:
    name: local
    
    
