
server:
  port: 8081


spring:
  application:
    name: mail-sender

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sender-db
    username: admin
    password: 123456
    initialize: true

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 9822c606cd42b0
    password: d8d12800be7995
    properties:
      mail:
        smtp:
          auth: true
          starttls: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    mail:
      sender:
        rabbitmq: DEBUG
        services: DEBUG

app-config:


  rabbit:
    exchange:
      mail: mail.exchange

    routingKey:
      mail: mail-confirmation.routingKey

    queue:
      mail: mail-confirmation.queue
