
server:
  port: 8081


spring:
  application:
    name: mail-sender


  data:
    mongodb:
      uri: mongodb://admin:123456@localhost/email-db?authSource=admin

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 9822c606cd42b0
    password: d8d12800be7995
    properties:
      mail:
        smtp:
          auth: true
          starttls: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    mail:
      sender:
        rabbitmq: DEBUG
        services: DEBUG

app-config:


  rabbit:
    exchange:
      mail: mail.exchange

    routingKey:
      mail: mail-confirmation.routingKey

    queue:
      mail: mail-confirmation.queue
